language: ruby
rvm:
  - 2.1.5
  - 2.2.2
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate test
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails4252.gemfile
