language: ruby
rvm:
  - 2.3.3
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate test
gemfile:
  - gemfiles/rails506.gemfile
  - gemfiles/rails521.gemfile
  - gemfiles/rails522.gemfile
